version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wannago
      MYSQL_USER: john
      MYSQL_PASSWORD: 12345
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
